/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.maestredam.qa.views;

import es.maestredam.qa.model.GestorInfo;
import es.maestredam.qa.model.Usuario;
import es.maestredam.util.LinkedList;
import javax.swing.JCheckBox;

/**
 *
 * @author Luismi
 */
public class AniadirUser extends javax.swing.JDialog{

    
    public AniadirUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombreComp = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        txtNombCom = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        chkAdmin = new javax.swing.JCheckBox();
        txtClave = new javax.swing.JPasswordField();
        lblAddUser = new javax.swing.JLabel();
        lblRepeUsu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombre.setLabelFor(txtNombre);
        lblNombre.setText("Nombre:");
        lblNombre.setToolTipText("");

        lblNombreComp.setLabelFor(txtNombCom);
        lblNombreComp.setText("Nombre completo:");

        lblClave.setLabelFor(txtClave);
        lblClave.setText("Clave:");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        chkAdmin.setText("Administrador");

        lblAddUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAddUser.setText("Añadir usuario");

        lblRepeUsu.setVisible(false);
        lblRepeUsu.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        lblRepeUsu.setText("El usuario ya existe, vuelva a introducirlo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAddUser)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRepeUsu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClave)
                                    .addComponent(lblNombreComp))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(txtNombCom)
                                    .addComponent(txtClave))))
                        .addGap(133, 133, 133))))
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(chkAdmin)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(lblAddUser)
                .addGap(36, 36, 36)
                .addComponent(lblRepeUsu)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreComp)
                    .addComponent(txtNombCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClave)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnCrear)
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private Usuario user;
    
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        user = new Usuario(txtNombre.getText(),txtNombCom.getText(),txtClave.getText(),chkAdmin(chkAdmin));
        Usuario comparador;
        boolean existe=false;
        LinkedList<Usuario> lista;
        GestorInfo gestor = new GestorInfo("usuarios.dam");
        lista = gestor.cargarArchivo();
        if(lista.size()==0){
            lista.add(user);
            gestor.escribirLista(lista, false);
                dispose();
        }else{
            for (int i = 0; i < lista.size(); i++) {
                comparador=lista.get(i);
                if(user.getNombre().equals(comparador.getNombre())){
                    existe=true;
                }
            }
            if(existe){
                lblRepeUsu.setVisible(true);
            }else{
                lista.add(user);
                gestor.escribirLista(lista, false);
                dispose();
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed
    private boolean chkAdmin(JCheckBox cb1){
        boolean admin=false;
        if(cb1.isSelected()){
            admin=true;
        }
        return admin;
    }
    
    public Usuario getNewUser(){
        return user;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AniadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AniadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AniadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AniadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AniadirUser dialog = new AniadirUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JLabel lblAddUser;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreComp;
    private javax.swing.JLabel lblRepeUsu;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtNombCom;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
