/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.maestredam.qa.views;

import es.maestredam.qa.model.GestorInfo;
import es.maestredam.qa.model.Pregunta;
import es.maestredam.util.LinkedList;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author Luismi
 */
public class Jugar extends javax.swing.JDialog {
    private GestorInfo gestor = new GestorInfo("preguntas.dam");
    private Pregunta pregunta;
    private boolean seguir = true;
    private int contador = 0;
    private Set<Integer> numGenerados = new HashSet<>();
    LinkedList<Pregunta> lista = gestor.cargarArchivo();
    private int puntuacion;
    /**
     * Creates new form Jugar
     */
    public Jugar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnGroup.add(rdoA);
        btnGroup.add(rdoB);
        btnGroup.add(rdoC);
        getPregunta();
    }
    
    private void getPregunta(){
        int random;
        boolean distinto = false;
        if(seguir && contador<5){
            while(!distinto){
                random = (int)(Math.random()*(lista.size()));
                if(!numGenerados.contains(random) && seguir){
                    numGenerados.add(random);
                    pregunta = lista.get(random);
                    setPregunta();
                    distinto=true;
                }
            }
        }else if(contador==5){
            puntuacion = Integer.parseInt(txtPunt.getText());
            dispose();
        }
    }
    
    private void setPregunta(){
        lblPreg.setText(pregunta.getEnunciado());
        lblCat.setText(pregunta.getCategoria());
        if(pregunta.getRespuestaB()==null){
            rdoA.setVisible(false);
            rdoB.setVisible(false);
            rdoC.setVisible(false);
            txtResp.setText("");
            txtResp.setVisible(true);
        }else{
            txtResp.setVisible(false);
            lblResp.setVisible(false);
            rdoA.setVisible(true);
            rdoB.setVisible(true);
            rdoC.setVisible(true);
            rdoA.setSelected(false);
            rdoB.setSelected(false);
            rdoC.setSelected(false);
            rdoA.setText(pregunta.getRespuestaA());
            rdoB.setText(pregunta.getRespuestaB());
            rdoC.setText(pregunta.getRespuestaC());
        }
        seguir = false;
    }
    
    public int getPuntuacion(){
        return puntuacion;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblEnun = new javax.swing.JLabel();
        lblPunt = new javax.swing.JLabel();
        txtPunt = new javax.swing.JTextField();
        lblPreg = new javax.swing.JLabel();
        txtResp = new javax.swing.JTextField();
        lblResp = new javax.swing.JLabel();
        rdoA = new javax.swing.JRadioButton();
        rdoB = new javax.swing.JRadioButton();
        rdoC = new javax.swing.JRadioButton();
        btnConf = new javax.swing.JButton();
        lblCat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblEnun.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblEnun.setText("Enunciado:");

        lblPunt.setText("Puntuación");

        txtPunt.setEditable(false);
        txtPunt.setText("0");

        lblPreg.setText("jLabel1");

        lblResp.setText("Respuesta");

        rdoA.setText("jRadioButton1");

        rdoB.setText("jRadioButton2");

        rdoC.setText("jRadioButton3");

        btnConf.setText("Confirmar");
        btnConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfActionPerformed(evt);
            }
        });

        lblCat.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPunt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPunt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoC)
                                    .addComponent(rdoB)
                                    .addComponent(rdoA)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblResp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnun)
                        .addGap(68, 68, 68)
                        .addComponent(lblCat)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(btnConf)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnun)
                    .addComponent(lblCat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnConf)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPunt)
                    .addComponent(txtPunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfActionPerformed
        seguir = true;
        int extraida;
        int indice;
        contador++;
        if(pregunta.getRespuestaB()==null){
            if(pregunta.compruebaNormal(txtResp.getText(), pregunta) == true){
                puntuacion = Integer.parseInt(txtPunt.getText());
                puntuacion++;
                txtPunt.setText(""+puntuacion);
            }
        }else{
            if(rdoA.isSelected()){
                if(pregunta.compruebaTest(rdoA.getText(), pregunta)){
                    puntuacion = Integer.parseInt(txtPunt.getText());
                    puntuacion+=1;
                    txtPunt.setText(""+puntuacion);
                }
            }else if(rdoB.isSelected()){
                if(pregunta.compruebaTest(rdoB.getText(), pregunta)){
                    puntuacion = Integer.parseInt(txtPunt.getText());
                    puntuacion+=1;
                    txtPunt.setText(""+puntuacion);
                }
            }else if(rdoC.isSelected()){
                if(pregunta.compruebaTest(rdoC.getText(), pregunta)){
                    puntuacion = Integer.parseInt(txtPunt.getText());
                    puntuacion+=1;
                    txtPunt.setText(""+puntuacion);
                }
            }  
        }
        extraida = (pregunta.getVecesExtraida())+1;
        indice = lista.indexOf(pregunta);
        lista.get(indice).setVecesExtraida(extraida);
        gestor.escribirLista(lista, false);
        getPregunta();
    }//GEN-LAST:event_btnConfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jugar dialog = new Jugar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConf;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblEnun;
    private javax.swing.JLabel lblPreg;
    private javax.swing.JLabel lblPunt;
    private javax.swing.JLabel lblResp;
    private javax.swing.JRadioButton rdoA;
    private javax.swing.JRadioButton rdoB;
    private javax.swing.JRadioButton rdoC;
    private javax.swing.JTextField txtPunt;
    private javax.swing.JTextField txtResp;
    // End of variables declaration//GEN-END:variables
}
